spring.security.user.name=bruno
spring.security.user.password=heavy-duty
server.servlet.session.timeout=30m
server.port=${PORT:8080}
spring.security.user.name=bruno
spring.security.user.password=renata
spring.security.form-login.default-success-url=/dashboard
